[package]
name = "forastilka"
version = "0.1.0"
edition = "2024"

[dependencies]
display-interface-spi = "0.5.0"
embassy-embedded-hal = "0.3.0"
embassy-sync = "0.6.2"
embedded-hal = "1.0.0"
embedded-sdmmc = "0.8.1"
esp-hal = { version = "0.23.1", features = ["esp32s3"] }
esp-println = "0.13.1"
fugit = "0.3.7"
mipidsi = "0.9.0"
static_cell = "2.1.0"
